"""Map Assemblyline types to Azul types."""

from typing import Optional

RECOGNIZED_TYPES: dict[str, Optional[str]] = {
    "android/apk": "APK",
    "android/dex": None,
    "android/resource": None,
    "android/xml": None,
    "archive/7-zip": "7ZIP",
    "archive/ace": "ACE",
    "archive/ar": "AR",
    "archive/audiovisual/flash": None,
    "archive/bzip2": "BZIP",
    "archive/cabinet": "CAB",
    "archive/cart": "CART",
    "archive/chm": "CHM",
    "archive/cpio": None,
    "archive/gzip": "GZIP",
    "archive/iso": "ISO",
    "archive/lzma": "LZMA",
    "archive/rar": "RAR",
    "archive/tar": "TAR",
    "archive/tnef": None,
    "archive/unknown": None,
    "archive/xz": None,
    "archive/zip": "ZIP",
    "audiovisual/afs": None,
    "audiovisual/acb": None,
    "audiovisual/flash": None,
    "audiovisual/fsb": None,
    "audiovisual/unknown": None,
    "certificate/rsa": None,
    "code/animation/ccb": None,
    "code/autorun": None,
    "code/batch": "Text",
    "code/c": "Text",
    "code/css": "Text",
    "code/csharp": "Text",
    "code/postscript": "Text",
    "code/erlang": "Text",
    "code/gles": "Text",
    "code/glsl": "Text",
    "code/go": "Text",
    "code/hta": "Text",
    "code/html": "Text",
    "code/java": "Text",
    "code/javascript": "Text",
    "code/jscript": "Text",
    "code/ida": "Text",
    "code/lisp": "Text",
    "code/nu": "Text",
    "code/pdfjs": "Text",
    "code/perl": "Text",
    "code/php": "Text",
    "code/ps1": "Text",
    "code/python": "Text",
    "code/ruby": "Text",
    "code/rust": "Text",
    "code/shell": "Text",
    "code/sgml": "Text",
    "code/sql": "Text",
    "code/vbe": "Text",
    "code/vbs": "Text",
    "code/wsf": "Text",
    "code/xml": "Text",
    "db/dbf": None,
    "db/sqlite": None,
    "document/installer/windows": None,
    "document/lotus/spreadsheet": None,
    "document/office/equation": None,
    "document/office/excel": "MS Excel Spreadsheet",
    "document/office/email": "Email",
    "document/office/hwp": None,
    "document/office/mhtml": None,
    "document/office/paintbrush": None,
    "document/office/package": None,
    "document/office/powerpoint": "MS PowerPoint Presentation",
    "document/office/passwordprotected": "MS Encrypted Document",
    "document/office/ole": "MS Encrypted Document",
    "document/office/onenote": None,
    "document/office/rtf": "Rich Text Format",
    "document/office/unknown": None,
    "document/office/visio": None,
    "document/office/word": "MS Word Document",
    "document/office/wordpro": None,
    "document/office/wordperfect": None,
    "document/email": "Email",
    "document/pdf": "PDF",
    "document/pdf/passwordprotected": "PDF",
    "document/pdf/portfolio": "PDF",
    "document/unknown": None,
    "executable/unknown": None,
    "executable/mach-o": "Mach-O",
    "executable/windows/com": "DOS COM",
    "executable/windows/dos": "DOS EXE",
    "executable/windows/pe": "Win32 EXE",
    "executable/windows/pe32": "Win32 EXE",
    "executable/windows/pe64": "Win32 EXE",
    "executable/windows/dll32": "Win32 DLL",
    "executable/windows/dll64": "Win32 DLL",
    "executable/linux/elf32": "ELF",
    "executable/linux/elf64": "ELF",
    "executable/linux/so32": None,
    "executable/linux/so64": None,
    "font/texture/pvr": None,
    "image/bmp": None,
    "image/emf": None,
    "image/gif": None,
    "image/icon": None,
    "image/jpg": None,
    "image/png": None,
    "image/svg": None,
    "image/webp": None,
    "image/wmf": None,
    "image/texture/ka3d": None,
    "image/texture/ktx": None,
    "image/texture/pkm": None,
    "image/texture/powervr": None,
    "image/texture/rvio": None,
    "image/unknown": None,
    "ios/ipa": None,
    "java/class": "Java Bytecode",
    "java/jar": None,
    "java/java": None,
    "java/jbdiff": None,
    "java/manifest": None,
    "java/signature": None,
    "java/unknown": None,
    "meta/torrent": None,
    "meta/shortcut/windows": None,
    "metadata/memorydump": None,
    "metadata/sysmon": None,
    "metadata/iccprofile": None,
    "network/sff": None,
    "network/tcpdump": "Network capture",
    "network/unknown": None,
    "resource/big": None,
    "resource/ccz": None,
    "resource/cpk": None,
    "resource/dz": None,
    "resource/mo": None,
    "resource/pak": None,
    "resource/ptc": None,
    "resource/sbm": None,
    "resource/sbr": None,
    "resource/sc": None,
    "resource/unity": None,
    "text/plain": "Text",
    "text/calendar": "Text",
    "text/json": "Text",
    "text/markdown": "Text",
    "quarantine/ahnlab": None,
    "quarantine/avast": None,
    "quarantine/avira": None,
    "quarantine/mcafee": None,
    "quarantine/windowsdefender": None,
    "unknown": None,
}

# map specific groups as a fallback
RECOGNIZED_GROUPS = {
    "text": "Text",
    "code": "Text",
}


def map_type(incoming_type: str) -> Optional[str]:
    """Return the Azul type for the given Assemblyline type."""
    try:
        mapped = RECOGNIZED_TYPES[incoming_type]
    except KeyError:
        group = incoming_type.split("/")[0]
        try:
            mapped = RECOGNIZED_GROUPS[group]
        except KeyError:
            mapped = None

    return mapped
